"""
Patterns
"""
type PatternPage {
    id: ID!
    name: String!
    userID: String!
    location: Location!
    patternFile: String!
    visibility: String!
    catalogData: Map
    canSupport: Boolean!
    errmsg: String
    createdAt: String
    updatedAt: String
}

type PatternResult {
    id: ID!
    name: String!
    userID: String!
    location: Location!
    patternFile: String!
    visibility: String!
    catalogData: Map
    canSupport: Boolean!
    errmsg: String
    createdAt: String
    updatedAt: String
}

type PatternPageResult {
    page: Int!
    pageSize: Int!
    totalCount: Int!
    patterns: [PatternResult]
}