"""
Performance
"""
type PerfPageResult{
    page: Int!
    pageSize: Int!
    totalCount: Int!
    results: [MesheryResult]
}

type PerfProfile {
    concurrentRequest: Int!
    createdAt: String
    duration: String!
    endpoints: [String]
    id: String!
    lastRun: String
    loadGenerators: String
    name: String
    qps: Int
    totalResults: Int
    updatedAt: String
    userID: String
    request_headers: String
    request_cookies: String
    request_body: String
    content_type: String
    service_mesh: String
}

type PerfPageProfiles {
    page: Int!
    pageSize: Int!
    totalCount: Int!
    profiles: [PerfProfile]
}